---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: ghcr.io/home-operations/sonarr
    pullPolicy: IfNotPresent
    tag: "4.0.16.2946"

  service:
    port: 8989

  resources:
    requests:
      cpu: 50m
      memory: 200Mi

  httpRoute:
    enabled: true
    hostnames: [plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
    rules:
      - port: 8989
        matches:
          - path:
              type: PathPrefix
              value: /sonarr

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 2Gi

  deploymentStrategy:
    type: Recreate

  probes:
    initialDelaySeconds: 15
    type: tcpSocket
    options:
      port: http

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  config:
    SONARR__AUTH__METHOD: External
    SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
    SONARR__POSTGRES__MAINDB: sonarr-main
    SONARR__POSTGRES__LOGDB: sonarr-log
    SONARR__SERVER__URLBASE: sonarr
    TZ: Europe/London

  env:
    - name: SONARR__POSTGRES__HOST
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-sonarr
          key: host
    - name: SONARR__POSTGRES__USER
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-sonarr
          key: user
    - name: SONARR__POSTGRES__PASSWORD
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-sonarr
          key: password

  volumes:
    - name: media
      hostPath:
        path: /plex

  volumeMounts:
    - mountPath: /data
      name: media

  netpol:
    enabled: true
    allowCoredns: true
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gateways
            podSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: public
        ports:
          - port: 8989
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: monitoring
            podSelector:
              matchLabels:
                app.kubernetes.io/name: uptime-kuma
        ports:
          - port: 8989
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: organizr
        ports:
          - port: 8989
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: prowlarr
        ports:
          - port: 8989
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: prowlarr
        ports:
          - port: 9696
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: transmission
        ports:
          - port: 9091
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: crunchy
            podSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: crunchy
        ports:
          - port: 5432
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 10.0.0.0/8
        ports:
          - port: 443
