apiVersion: v2
name: loki
description: loki helm chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: loki
    version: "13.2.5"
    repository: https://grafana-community.github.io/helm-charts/
