apiVersion: v2
name: renovate-operator
description: A Helm chart to redeploy resources and pull new images in
type: application
version: 0.1.0
dependencies:
  - name: renovate-operator
    repository: oci://ghcr.io/mogenius/helm-charts
    version: 4.12.1
