stages:
  - lint
  - plan
  - deploy
  - renovate

image: ghcr.io/henrywhitaker3/containers/pipelines@sha256:d97b1a45a06c42c214634ecc4d35adb330a946ee514457d3a7f7fe7004471388

##############
# Kubernetes #
##############
diffs:
  stage: plan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - ./scripts/pipeline_changes.sh

###########
# Ansible #
###########
.playbooks:
  variables:
    ANSIBLE_CONFIG: ./ansible.cfg
  parallel:
    matrix:
      - PLAYBOOK:
          - jump
          - k3s
          - haproxy
          - adguard
          - proxmox
          - netbird
  rules:
    - if: $SKIP_ANSIBLE == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "main" && $ANSIBLE_RUN_ALL == "true"
    - if: $CI_COMMIT_BRANCH == "main" && $SKIP_ANSIBLE != "true"
      changes:
        - ansible/playbooks/$PLAYBOOK/*
        - ansible/playbooks/$PLAYBOOK/**/*
        - ansible/inventory/*
        - ansible/inventory/**/*
        - ansible/roles/**/*
        - ansible/inventory
        - .ansible-lint

ansible lint:
  stage: lint
  extends: .playbooks
  script:
    - task age_key="$AGE_KEY" ci:age:key
    - task playbook="ansible/playbooks/$PLAYBOOK/main.yaml" ci:lint

ansible play:
  stage: deploy
  extends: .playbooks
  script:
    - eval $(ssh-agent -s)
    - task playbook="ansible/playbooks/$PLAYBOOK/main.yaml" age_key="$AGE_KEY" ssh_key="$SSH_KEY" ci:playbook
  environment:
    name: "$PLAYBOOK"

#############
# Terraform #
#############
.terraform:base:
  image: ghcr.io/henrywhitaker3/containers/pipelines@sha256:d97b1a45a06c42c214634ecc4d35adb330a946ee514457d3a7f7fe7004471388
  before_script:
    - task age_key="$AGE_KEY" ci:age:key
    - git config --global --add safe.directory /builds/henrywhitaker3/homelab
    - task tm:init
  rules:
    - if: $SKIP_TERRAFORM == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "main" && $SKIP_TERRAFORM != "true"
      changes:
        - terraform/**/*
        - .gitlab-ci.yml
  variables:
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
    TF_VAR_infra_state_url: https://gitlab.com/api/v4/projects/45412263/terraform/state/tf-state
    TF_VAR_infra_state_token: $TERRAFORM_ACCESS_TOKEN
    SOPS_AGE_KEY_FILE: ~/.age.key
    SOPS_AGE_KEY: $AGE_KEY

tf plan:
  stage: plan
  extends:
    - .terraform:base
  script:
    - task tm:plan -- -out out.tfplan
  artifacts:
    paths:
      - terraform/**/out.tfplan
  rules:
    - !reference [.terraform:base, rules]

tf deploy:
  stage: deploy
  extends:
    - .terraform:base
  script:
    - task tm:apply -- -auto-approve out.tfplan
  dependencies:
    - tf plan
  when: manual
