---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: ghcr.io/henrywhitaker3/ticktick-events
    pullPolicy: IfNotPresent
    tag: v1.1.1

  resources:
    requests:
      cpu: 15m
      memory: 24Mi

  entrypoint:
    args:
      - --log-level
      - debug
      - --redis-url
      - dragonfly.dragonfly.svc.cluster.local:6379

  probes:
    enabled: false

  env:
    - name: TICKTICK_TOKEN
      valueFrom:
        secretKeyRef:
          name: ticktick-secrets
          key: ticktick-token
    - name: PAVLOK_TOKEN
      valueFrom:
        secretKeyRef:
          name: ticktick-secrets
          key: pavlok-token
    - name: QUIET_TIMES_MONDAY
      value: &weekday "23:00:00-08:00:00"
    - name: QUIET_TIMES_TUESDAY
      value: *weekday
    - name: QUIET_TIMES_WEDNESDAY
      value: *weekday
    - name: QUIET_TIMES_THURSDAY
      value: *weekday
    - name: QUIET_TIMES_FRIDAY
      value: *weekday
    - name: QUIET_TIMES_SATURDAY
      value: &weekend "00:00:00-10:00:00"
    - name: QUIET_TIMES_SUNDAY
      value: *weekend
