netbird_setup_key: ENC[AES256_GCM,data:SwOk2ZO5xZaVSj7vCjXeQYBpfv8rE4MNtEzpBTv0JU/lwPWS,iv:2JaHjYsk+2ujZijrmFafl6wGyIgOLWIRhUsfZcA1wgM=,tag:hCEd4mauJPb04mzBnG1wnQ==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdmY5eTU1QTl4aitpbDIx
            RWxta1E2cDNoVTNHZmdnV1IyYVpiZWJGeTA4CnVnUUZTOEp5OXltK2Jxb2prdml0
            TUplRGpCV1RNSWNFZStmWVJCRFRESG8KLS0tIDBZUXo4TGk3ZklFM0h6dC9hVmNv
            V0FwdU5DbmNhdE5UU2g2TkI4SDNtcnMKD3AA46b7F/qb1Sl4TXHP8X8stz9zRZN+
            GdlH9qWJd4vcmp27so2agT4cqOgsDdGiMAuXedcRtCfKXwgLZZ1msw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:04:15Z"
    mac: ENC[AES256_GCM,data:d0sDMfg4mS2yWEeuLohM6O1hGuL4+QQ+zajdf+e6kV9cEUiBoVtUe5uLN2W5C6RglAWoIMRYbGCS+Q5cynaX1gQvpH8VZMIHhj0M5CA2IiuT5zXj7w/zNWYoyxGIeMg0142zCPPDoAmcs1JI+CgQBDi3pSTbKeIjAR2b0LqvujU=,iv:ftjGbHIN7MKG/m5NOEktfiSolMwo3XjG9xvLsdQcvHg=,tag:lX+A8//iC7axPnFqiTkZ2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
