netbird_setup_key: ENC[AES256_GCM,data:F15KGqdh80Fn80vK4YeYfH+I63FegIcmCe9/g6VUNQzZFtFl,iv:yY/vAuqrkyOofYrjAu9xIhYbgeKV/Dc9rFHlecibbE0=,tag:q30C/NVMr2J2fZpgTIVlSA==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNk5UMEk4bjIzTGVVZmZ0
            UWJ3VzZiS0RySTBVdDNMMTE5eUdIdklLaVVVCkJFVHNMaWxKNGVWK2RrczJTN28v
            SnlkZDdyVmZoaGhTUThxOXQ2NTU5OWsKLS0tIHdJT3NiZkZLSG4xSzJibnMyQWZZ
            US9yV29odUVtZ1RRcmxCbEV4a2RKYUEKA5b9O/24ahXIZRPy/NY79b1mIPSQr+66
            Z/FM8uhwma5BLvjaSqnUJwU2LiwVqUQMW5UnLgrBrmHidKGO/OxqFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:04:05Z"
    mac: ENC[AES256_GCM,data:bPf1W4Ucgz9Cgv/L8AQQWbvT5G4StfTO5Exuum0HSBzrWzjAfRgbgyHPe1mac7GtALzHSww7IOTW6v1Mw8QYErdz1iRAesyfsgC0jnQbSwGcOPbTE+Tz6UQhllAEJNiPRjZO4NzdneHAe0xHuYviji7rASMjxUrNfgkxORHHj7s=,iv:C9hJZNLN0UOwCHkJD7YXw2OCEr6bqjTtmi6JX3N+19w=,tag:5NFxoYJC7R/zyEPFMN+naQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
