healthcheck: ENC[AES256_GCM,data:AKN4w+MuDBuA55dy1CErWMej86NND55AMP3nkfHt14Sf45bkwrnCQAUEoyp4GY7cXt8u6wTeK+M=,iv:/IvMQZo/pL6D3Szeu44XCBoElduiEniJigN5dF9haYw=,tag:NIGgYoxpdBAd4RCQ2lZhMg==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:2H9iaCEyHP4NALF0VD7iC2/mtUe/AQ31tNBQX099IjzV1WFJ,iv:gtdf//0yjJQ1NalhkVwqKbqWZwGI+xYRgRfiMfBsb0I=,tag:ZYSOOZ9NlMZxjCmHp1edYA==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2JxeFFCaDFhdVdYNWFO
            QldycjNQMmNVVk1IZWw3djBCV3RKa3IwVEhZCkdhT25VbWlCNnBneE1JRDNheU1Z
            eVZTWFZ1SnFQYmsrNnhWQ3E3azVyRjgKLS0tIHRmSXNrZVpwVW1nZkZOK3k4d0RP
            allwbnF4RHN5OHlBNEVGcm80bHIvb28Kdfpdi3He0/zhA6zfwX1lFcuR77zoamhn
            o08TjouC8xKPcseOBS4k88DKYXUXHmWp8iJhW05H4ft5v81lyxKBYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:04:41Z"
    mac: ENC[AES256_GCM,data:yzBoVEgBcTPPVdXGa0I/HSGnEX7ld4qO9mlTQNp1DZFGA2HJgxlX3c8LtRQczEsOaViz5hQAYR2W016AOhSejx5nArabFldbF5SmOW29bEI/nGqVKbm4NhE4gOvdvQ8+XuSdHQdCfOO1GaOO0iwyKX5V2X74maTL6Kfc78CwHwQ=,iv:2I7gGuvz93t/zP5NBDuU90hqJNsdaeWqBE1VIDZc6vc=,tag:tSjqJr/ADW0C0t5QTf5QGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
