healthcheck: ENC[AES256_GCM,data:fMWPotGKMNEgJptLfMwbG/38qyS6411jxDY2J8QLI+WD7JvC2mgBte/KJgPVEOKDZC18/J0IBSY=,iv:t9WCKVcnjqVYLHjlQ5xPNgmAnbbE8OadQPUDzf8OZ5g=,tag:iXk1EyeaOP8ucnVyrDDR5A==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:O9xVrZCSoWqN7pd8ucp+16p0gFwiQUuEK0IpAWUluKJaNWB+,iv:OF7qT8NSHBpC21PfExGV94gff0cBwGm59dT0GX32NLE=,tag:iYroL6Pdg7HJeHuuM1JCTg==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cXJZVUQ1SjZ5dk5YTlZK
            TmxCbmpVYTZpNTM2cmxoQlpxaVN4NmowK1dBClN6RzY5cGc1TTYrejFTd21mNFU5
            djhIYmtyL0o1VDJQZVJaZ2JmVnJHSzgKLS0tIGdlV3VJWHRId1VwQi9jTy80d3JM
            bVI3N21Id2tHTkVrR0Q2SFhIdHo3a1UKaQLcVxS0zc/kLoGYSHeYl9/1CPwNcb+h
            VLlXry2w74rTCfVppy7fAFElsbR4NkhbnEC9Di/89X+WORAE4b+EWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:05:01Z"
    mac: ENC[AES256_GCM,data:jJUIQTwqkEEZxxuGYOh0VFAqLcD1gwZvqyuU5qnP9KeW+smyONu+h+VQvpOWhs+aM0JgtPNiuXQ9To+OKBATIRkza5qRVNOmBUfchXiz7/t29r4QgShUzVyaB+SR5gFiWY8cToJ6gYTQWmX9vCMELz0QZv4/l1IKSCYa/cZPAj0=,iv:PEBDiMZvUFY6LDxvHyQ8CNnboze5UoA5OLT7Eq5an5o=,tag:Gv+uie2sgzEkH16ZIppCAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
