healthcheck: ENC[AES256_GCM,data:s5dKnKSc17sbTtL9jMt54woj6KBYjgUMoHz+QiiW+PBAGVJcZp1ib36HOBhid1DG2w61uzFIbFw=,iv:iJGD0UtIDehT8TRTRhfJbBRa7NM+zoenZP0leZlgGcc=,tag:5vffs7Svtfgh9gyr2+mi5Q==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:+dVIIwwFLXHW55G7oNxqkcFb1qN/tMYSRSNfwFk41dutWCmk,iv:M1Be8/M3Sg3NyQDPf8yjLCkiW5t1aEtGaGk/DFBXIlk=,tag:hSxKJKuVTF96vwT19NjCow==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cXJZVUQ1SjZ5dk5YTlZK
            TmxCbmpVYTZpNTM2cmxoQlpxaVN4NmowK1dBClN6RzY5cGc1TTYrejFTd21mNFU5
            djhIYmtyL0o1VDJQZVJaZ2JmVnJHSzgKLS0tIGdlV3VJWHRId1VwQi9jTy80d3JM
            bVI3N21Id2tHTkVrR0Q2SFhIdHo3a1UKaQLcVxS0zc/kLoGYSHeYl9/1CPwNcb+h
            VLlXry2w74rTCfVppy7fAFElsbR4NkhbnEC9Di/89X+WORAE4b+EWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:05:16Z"
    mac: ENC[AES256_GCM,data:/hBiFcd/67j0LuCj4WUAFmbAn/fGy2KklKb9f+hgZl7vP4irHbtahNxZL1nQAWXwuz1Pa7FqG0qIdeN4W546Fi4Nff7GfW/FdBwtcm4YfNSfqpuQUqqvy/bXDj/sXcJ4ZxPiJoT+b5K9FBS/fSWmWdQJaqEiyCjIGaqtACdIJ90=,iv:F8CrpGkzqtLbOWcSOKOjxaQokfDgG8sIS7R9jRvQQKI=,tag:hTD3+BBroNiiEkKeXsRTbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
