healthcheck: ENC[AES256_GCM,data:cHfH9uAgjiLWocVmC5qXP5mlYfZJBgvfkZSQbf21TELkc2+qXL8/0YkXdzhGRNRJF7SBJs1QSfU=,iv:thrCPiprP3gwgRslWg6pxPwszeY/rqPhW3YtZQ45ZMU=,tag:UyP3ZpCkqCtFr49yeFTn1g==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:9b5bLc30jprsahhAnSak1/zVfV9RFCnnePu0lSQJhnjf3UdS,iv:J9ohJX79RQK57AneJGbXjxU+nqCb8pIF0Sdv90+jGkI=,tag:F8v8Qb2d0gqds3JuuJokgg==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aW1NclRES1NQTVhLMGZK
            dXhKdW1CWFZGQjF6dERJS0RRY2dBdndocWlVCjYyL2FtTEFxL1Q0NXNLL2lQT1k1
            U1Zod0Fja2xDZGVudlNQSHdBaWwxbWsKLS0tIFFMUklzMjFnRmhYMTdUeEl6Mi81
            S0h1MlB6dUJhQ0thVndJNzJZNFd0Mk0KqtLNWGMjbgALTQMpfwJcMEaqEWUcScwY
            AfSswSl8MRh3IFiWkPZc6iKQvfhqV4RV4d36sMlXaEd5jrM2cljYLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:05:31Z"
    mac: ENC[AES256_GCM,data:JmOoGVK2HYrgnJ43a0WEQuJjs4tsHc4bXBa1DgdsN4GrjYR5oji7FJ5f6ITKC0ddQWGY9d/Fhi2LKbyRliJp54nPEQAofHfJ3ZDSejTQMlajHgnscKrTxyXPJ6ez7wddCCYlr6kqmgL4iVV4EZOPCGZm+0ABdb6JqTHZ5uhagDg=,iv:ie2ERAH2EZCk4I3iJYe+lTr57I4RkLZHDe5GK4qi8MY=,tag:l1Orq1X0K1Zycz48k8q+iA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
