---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  storageClassName: longhorn-no-backups
  resources:
    requests:
      storage: 50Gi
  accessModes: [ReadWriteOnce]
