---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: ghcr.io/home-operations/radarr
    pullPolicy: IfNotPresent
    tag: "6.1.1.10317"

  service:
    port: 7878

  resources:
    requests:
      cpu: 50m
      memory: 650Mi

  httpRoute:
    enabled: true
    hostnames: [plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
    rules:
      - port: 7878
        matches:
          - path:
              type: PathPrefix
              value: /radarr

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 4Gi

  deploymentStrategy:
    type: Recreate

  probes:
    initialDelaySeconds: 15

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  config:
    RADARR__URL_BASE: radarr
    RADARR__POSTGRES_MAIN_DB: radarr-main
    RADARR__POSTGRES_LOG_DB: radarr-log
    RADARR__AUTHENTICATION_METHOD: External
    RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses

  env:
    - name: RADARR__POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-radarr
          key: host
    - name: RADARR__POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-radarr
          key: user
    - name: RADARR__POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-radarr
          key: password

  volumes:
    - name: media
      hostPath:
        path: /plex

  volumeMounts:
    - mountPath: /data
      name: media

  netpol:
    enabled: true
    allowCoredns: true
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gateways
            podSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: public
        ports:
          - port: 7878
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: monitoring
            podSelector:
              matchLabels:
                app.kubernetes.io/name: uptime-kuma
        ports:
          - port: 7878
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: seerr
        ports:
          - port: 7878
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: organizr
        ports:
          - port: 7878
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: prowlarr
        ports:
          - port: 7878
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: prowlarr
        ports:
          - port: 9696
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: media
            podSelector:
              matchLabels:
                app.kubernetes.io/name: transmission
        ports:
          - port: 9091
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: crunchy
            podSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: crunchy
        ports:
          - port: 5432
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 10.0.0.0/8
        ports:
          - port: 443
