---
# yaml-language-server: $schema=https://raw.githubusercontent.com/henrywhitaker3/crds/refs/heads/main/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
  project: cluster
  sources:
    - path: kubernetes/k3s/bootstrap/manifests
      repoURL: https://gitlab.com/henrywhitaker3/homelab.git
      targetRevision: main
      directory:
        include: projects.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
