---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: plex
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: plex
  headers:
    earlyRequestHeaders:
      set:
        - name: x-real-ip
          value: "%REQ(X-ENVOY-EXTERNAL-ADDRESS)%"
