---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: plex-real-ip
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: plex
  lua:
    - type: Inline
      inline: |
        function envoy_on_request(request_handle)
          local real_ip = request_handle:headers():get("x-envoy-external-address")
          request_handle:logInfo("handling the ip " .. (real_ip or "nil"))
          if real_ip then
            request_handle:headers():remove("x-forwarded-for")
            request_handle:headers():add("x-forwarded-for", real_ip)
            request_handle:headers():remove("x-real-ip")
            request_handle:headers():add("x-real-ip", real_ip)
          end
        end
