---
- name: Add azlux apt repository
  tags: docker
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://packages.azlux.fr/debian/
    suites: "bullseye"
    components: stable
    architectures: amd64
    signed_by: https://azlux.fr/repo.gpg
    state: present

- name: Install packages
  become: true
  tags:
    - common
    - apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - bashtop
    - unzip

- name: Unattended upgrades
  ansible.builtin.import_tasks: unattended-upgrades.yaml
- name: Dotfiles
  ansible.builtin.import_tasks: dotfiles.yaml
  when: copy_dotfiles
