---
- name: Remove old repo
  tags: common
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/packages_azlux_fr_debian.list
    state: absent

- name: Add azlux apt repository
  tags: common
  become: true
  ansible.builtin.deb822_repository:
    name: azlux
    types: deb
    uris: https://packages.azlux.fr/debian/
    suites: trixie
    components: main
    architectures: amd64
    signed_by: https://azlux.fr/repo.gpg
    state: present

- name: Install packages
  become: true
  tags:
    - common
    - apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - bashtop
    - unzip

- name: Unattended upgrades
  ansible.builtin.import_tasks: unattended-upgrades.yaml
- name: Dotfiles
  ansible.builtin.import_tasks: dotfiles.yaml
  when: copy_dotfiles
