apiVersion: apps/v1
kind: Deployment
metadata:
  name: sloth
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: sloth
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits: null
        - name: git-sync-plugins
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits: null
