apiVersion: v2
name: netbird-operator
description: netbird-operator chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: netbird-operator
    alias: netbird-operator
    repository: oci://ghcr.io/netbirdio/helm-charts
    version: 0.8.0
