apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox
spec:
  staticConfigs:
    - targets:
        - https://plexmox.com
        - https://plex.plexmox.com
        - https://auth.plexmox.com
        - https://api.yourbuild.dev/auth/login
        - https://plexmox.com/sonarr
        - https://plexmox.com/radarr
        - https://plexmox.com/prowlarr
        - https://plexmox.com/tautulli
        - https://plexmox.com/transmission
  metricsPath: /probe
  params:
    module: [http_2xx]
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc:9115
