---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: seaweed-cluster
spec:
  staticConfigs:
    - targets:
        - seaweed.default.svc:9327
  metricsPath: /metrics
  relabelings:
    - targetLabel: job
      replacement: seaweed
