apiVersion: v2
name: oauth2-proxy
description: oauth2-proxy manifests
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: oauth2-proxy
    version: "10.1.4"
    repository: https://oauth2-proxy.github.io/manifests
