{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Metrics Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_storage_size_estimate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Health",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness == 0)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "count(longhorn_volume_robustness == 1)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(longhorn_volume_robustness == 2)",
     "legendFormat": "Degraded"
    },
    {
     "expr": "count(longhorn_volume_robustness == 3)",
     "legendFormat": "Faulted"
    }
   ]
  },
  {
   "title": "ArgoCD Sync",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(sync_status) (last_over_time(argocd_app_info[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (alertname, severity) (ALERTS)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAS Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n    node_filesystem_free_bytes{instance=\"unraid.lab:9100\", mountpoint=\"/mnt/user\"}\n        /\n    node_filesystem_size_bytes{instance=\"unraid.lab:9100\", mountpoint=\"/mnt/user\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "srep_request_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ArgoCD Health",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(health_status) (last_over_time(argocd_app_info[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD Apps",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (name, sync_status, health_status) (argocd_app_info)"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        avg by (pvc) (longhorn_volume_actual_size_bytes)\n    )\n        / \n    (\n        avg by (pvc) (longhorn_volume_capacity_bytes)\n    )\n) * 100",
     "legendFormat": "{{pvc}}"
    },
    {
     "expr": "100 - avg(100 * (minio_cluster_capacity_usable_free_bytes / minio_cluster_capacity_usable_total_bytes))",
     "legendFormat": "MinIO"
    },
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "Disk {{instance}}"
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "anomaly:node_cpu_seconds_idle_1d",
     "legendFormat": "CPU Idle {{instance}}"
    },
    { "expr": "anomaly:node_load5_1d", "legendFormat": "Load 5 {{instance}}" },
    {
     "expr": "anomaly:node_network_receive_bytes_1d",
     "legendFormat": "Rx {{instance}}"
    },
    {
     "expr": "anomaly:node_network_transmit_bytes_1d",
     "legendFormat": "Tx {{instance}}"
    },
    {
     "expr": "anomaly:longhorn_volume_read_latency_1d",
     "legendFormat": "PVC Read {{pvc}}"
    },
    {
     "expr": "anomaly:longhorn_volume_write_latency_1d",
     "legendFormat": "PVC Write {{pvc}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_disk_writes_completed_total{device=~\"sda|nvme.+\"}[$__rate_interval])) + sum by(instance) (irate(node_disk_reads_completed_total{device=~\"sda|nvme.+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total[$__rate_interval]))*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}