{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NAS Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n    node_filesystem_free_bytes{instance=\"unraid.lab:9100\", mountpoint=\"/mnt/user\"}\n        /\n    node_filesystem_size_bytes{instance=\"unraid.lab:9100\", mountpoint=\"/mnt/user\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD Sync",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(sync_status) (last_over_time(argocd_app_info[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (alertname, severity) (ALERTS)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{severity!=\"none\", alertstate=\"firing\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "($A / ($A + $B)) * 100", "type": "math" }
   ]
  },
  {
   "title": "ArgoCD Health",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(health_status) (last_over_time(argocd_app_info[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD Apps",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (name, sync_status, health_status) (argocd_app_info)"
    }
   ]
  },
  {
   "title": "Longhorn Volumes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        avg by (pvc) (longhorn_volume_actual_size_bytes)\n    )\n        / \n    (\n        avg by (pvc) (longhorn_volume_capacity_bytes)\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "anomaly:node_cpu_seconds_idle_1w",
     "legendFormat": "CPU Idle {{instance}}"
    },
    { "expr": "anomaly:node_load5_1w", "legendFormat": "Load 5 {{instance}}" },
    {
     "expr": "anomaly:node_network_receive_bytes_1w",
     "legendFormat": "Rx {{instance}}"
    },
    {
     "expr": "anomaly:node_network_transmit_bytes_1w",
     "legendFormat": "Tx {{instance}}"
    }
   ]
  }
 ]
}