{
 "title": "API",
 "tags": [ "srep" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Shells",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(srep_shells_connected)", "legendFormat": "Shells" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(srep_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "srep_request_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shell Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"srep/srep-api-chart\"} != `latency_human` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url) (srep_request_latency_seconds{url!=\"/plays/:id/shell\", url!=\"/plays/active/stream\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shell Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Endpoint Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(url) (rate(srep_requests_total{job=\"api\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"srep\", container=\"api\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(queue) (srep_queue_ready)",
     "legendFormat": "Backlog: {{queue}}"
    },
    {
     "expr": "sum by(queue) (srep_queue_inflight)",
     "legendFormat": "Inflight: {{queue}}"
    },
    {
     "expr": "sum by(queue) (srep_queue_rejected)",
     "legendFormat": "Rejected: {{queue}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"srep\", container=\"api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays Expired",
   "type": "timeseries",
   "description": "The number of plays that are expired",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "plays" } },
   "targets": [
    {
     "expr": "round(sum(increase(srep_plays_killed[$__rate_interval])), 1)",
     "legendFormat": "Plays killed"
    }
   ]
  }
 ]
}