generic:
  nameOverride: pocket-id
  fullnameOverride: pocket-id

  replicaCount: 1

  deploymentStrategy:
    type: Recreate

  image:
    repository: ghcr.io/pocket-id/pocket-id
    pullPolicy: IfNotPresent
    tag: "v2.3.0"

  service:
    port: 1411

  env:
    - name: APP_URL
      value: https://pocket.plexmox.com
    - name: LOG_JSON
      value: "true"
    - name: VERSION_CHECK_DISABLED
      value: "true"
    - name: FILE_BACKEND
      value: s3
    - name: ANALYTICS_DISABLED
      value: "true"
    - name: TRUST_PROXY
      value: "true"
    - name: S3_BUCKET
      value: pocketid
    - name: S3_REGION
      value: garage
    - name: S3_FORCE_PATH_STYLE
      value: "true"
    - name: S3_ENDPOINT
      value: https://garage.plexmox.com
    - name: UI_CONFIG_DISABLED
      value: "true"
    - name: LDAP_ENABLED
      value: "true"
    - name: LDAP_URL
      value: ldap://lldap.identity.svc.cluster.local:3890
    - name: LDAP_BIND_DN
      value: UID=pocketid,OU=people,DC=plexmox,DC=com
    - name: LDAP_BASE
      value: DC=plexmox,DC=com
    - name: LDAP_ADMIN_GROUP_NAME
      value: admin
    - name: LDAP_ATTRIBUTE_USER_UNIQUE_IDENTIFIER
      value: uuid
    - name: LDAP_ATTRIBUTE_USER_USERNAME
      value: uid
    - name: LDAP_ATTRIBUTE_USER_EMAIL
      value: mail
    - name: LDAP_ATTRIBUTE_USER_FIRST_NAME
      value: givenName
    - name: LDAP_ATTRIBUTE_USER_LAST_NAME
      value: sn
    - name: LDAP_ATTRIBUTE_USER_PROFILE_PICTURE
      value: jpegPhoto
    - name: LDAP_ATTRIBUTE_GROUP_UNIQUE_IDENTIFIER
      value: uuid
    - name: LDAP_ATTRIBUTE_GROUP_NAME
      value: cn
    - name: LDAP_BIND_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pocket-id-config
          key: ldap-password
    - name: S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: pocket-id-config
          key: access-key-id
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: pocket-id-config
          key: secret-access-key
    - name: DB_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-pocketid
          key: uri
    - name: ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: pocket-id-config
          key: encryption-key

  httpRoute:
    enabled: true
    hostnames: ["pocket.plexmox.com"]
    labels:
      traefik-instance: public
    parentRefs:
      - name: public
        namespace: traefik
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        port: 1411
