longhorn:
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: false
  upgradeCheck:
    enabled: false
  image:
    longhorn:
      manager:
        tag: v1.11.0-hotfix-1
      instanceManager:
        tag: v1.11.0-hotfix-2

  persistence:
    removeSnapshotsDuringFilesystemTrim: enabled

  metrics:
    serviceMonitor:
      # Disabled until helm metricrelabiling is possible
      enabled: false
