---
runner:
  githubConfigUrl: https://github.com/henrywhitaker3/homelab
  githubConfigSecret: arc-creds
  controllerServiceAccount:
    name: actions-runner-controller-gha-rs-controller
    namespace: actions-system
