---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: ghcr.io/jellyfin/jellyfin
    pullPolicy: IfNotPresent
    tag: "10.11.11"

  resources:
    requests:
      cpu: 1000m
      memory: 512Mi

  service:
    port: 8096

    additionalPorts:
      - name: clientdisc
        port: 7359
        protocol: UDP
        targetPort: clientdisc

  httpRoute:
    enabled: true
    hostnames: [jelly.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: internal
        namespace: gateways
    rules:
      - port: 8096
        matches:
          - path:
              type: PathPrefix
              value: /

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 20Gi

  deploymentStrategy:
    type: Recreate

  probes:
    type: tcpSocket
    options:
      port: http
    initialDelaySeconds: 20
    failureThreshold: 10

  config:
    JELLYFIN_PublishedServerUrl: "https://jelly.plexmox.com"

  securityContext:
    privileged: true

  additionalPorts:
    - name: clientdisc
      containerPort: 7359
      protocol: UDP

  volumes:
    - name: media
      hostPath:
        path: /plex
    - name: quicksync
      hostPath:
        path: /dev/dri
    - name: transcode
      emptyDir: {}

  volumeMounts:
    - mountPath: /plex
      name: media
    - mountPath: /dev/dri
      name: quicksync
    - mountPath: /config/transcodes
      name: transcode

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: quicksync
                operator: In
                values:
                  - available
