---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: aaronleopold/stump
    pullPolicy: IfNotPresent
    tag: "nightly@sha256:a0b4692db5ad27332dc4432ad78bafa7a350931846f22a842cc440b9468ed5d7"

  service:
    port: 10801

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  httpRoute:
    enabled: true
    hostnames: [stump.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
    rules:
      - port: 10801
        matches:
          - path:
              type: PathPrefix
              value: /

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: STUMP_PORT
      value: "10801"
    # - name: STUMP_VERBOSITY
    #   value: "3"
    - name: STUMP_ENABLE_KOREADER_SYNC
      value: "true"
    - name: STUMP_ENABLE_UPLOAD
      value: "true"
    - name: STUMP_OIDC_ENABLED
      value: "true"
    - name: STUMP_OIDC_ISSUER_URL
      value: https://pocket.plexmox.com
    - name: STUMP_OIDC_SCOPES
      value: "openid,email,profile,groups"
    - name: STUMP_OIDC_ALLOW_REGISTRATION
      value: "fasle"
    - name: STUMP_OIDC_DISABLE_LOCAL_AUTH
      value: "false"
    - name: STUMP_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: stump-secrets
          key: oidc-client-id
    - name: STUMP_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: stump-secrets
          key: oidc-client-secret

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 1Gi

  volumes:
    - name: books
      hostPath:
        path: /plex/Media/Stump/books

  volumeMounts:
    - mountPath: /books
      name: books

  deploymentStrategy:
    type: Recreate

  probes:
    enabled: true

  netpol:
    enabled: true
    allowCoredns: true
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gateways
            podSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: public
        ports:
          - port: 10801
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: monitoring
            podSelector:
              matchLabels:
                app.kubernetes.io/name: uptime-kuma
        ports:
          - port: 10801
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 10.0.0.0/8
        ports:
          - port: 443
