generic:
  nameOverride: yopass
  fullnameOverride: yopass

  replicaCount: 2

  image:
    repository: jhaals/yopass
    pullPolicy: IfNotPresent
    tag: "12.5.0"

  service:
    port: 1337

  entrypoint:
    args:
      - "--memcached=dragonfly.dragonfly.svc.cluster.local:11211"

  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 50Mi

  httpRoute:
    enabled: true
    labels:
      traefik-instance: public
    hostnames: [yopass.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: traefik
    rules:
      - port: 1337
        matches:
          - path:
              type: Exact
              value: /
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: auth-public
      - port: 1337
        matches:
          - path:
              type: PathPrefix
              value: /
