---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: ghcr.io/home-operations/prowlarr
    pullPolicy: IfNotPresent
    tag: "2.3.5.5323"

  service:
    port: 9696

  resources:
    requests:
      cpu: 50m
      memory: 200Mi

  podSecurityContext:
    # runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  httpRoute:
    enabled: true
    hostnames: [plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
    rules:
      - port: 9696
        matches:
          - path:
              type: PathPrefix
              value: /prowlarr

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 1Gi

  deploymentStrategy:
    type: Recreate

  probes:
    initialDelaySeconds: 15
    timeoutSeconds: 5

  config:
    PROWLARR__AUTH__METHOD: External
    PROWLARR__POSTGRES__MAINDB: prowlarr-main
    PROWLARR__POSTGRES__LOGDB: prowlarr-log

  env:
    - name: PROWLARR__POSTGRES__HOST
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-prowlarr
          key: host
    - name: PROWLARR__POSTGRES__USER
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-prowlarr
          key: user
    - name: PROWLARR__POSTGRES__PASSWORD
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-prowlarr
          key: password
