---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.k8s.cloudflare.com/originissuer_v1.json
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-token
      key: apiKey
