---
gateway-helm:
  global:
    imageRegistry: mirror.gcr.io
  crds:
    gatewayAPI:
      safeUpgradePolicy:
        enabled: false
  config:
    envoyGateway:
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
      extensionApis:
        enableBackend: true
