{{- range .Values.themes }}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: "{{ .route }}"
  namespace: "{{ .namespace }}"
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "{{ .route }}"
  lua:
    - type: Inline
      inline: |
        local path = nil
        local context = "[{{ .app }}] - "
        function envoy_on_request(request_handle)
            path = request_handle:headers():get(":path") or ""
            context = context .. path .. " - "
            request_handle:logInfo(context .. "running filter")
        end
        function envoy_on_response(response_handle)
            local headers = response_handle:headers()
            local content_type = headers:get("content-type") or ""

            if not (content_type and string.find(content_type, "text/html")) then
                response_handle:logInfo(context .. "not a html file it's a " .. content_type)
                return
            end
            response_handle:logInfo(context .. "its html, continuing the replacement")

            local body = response_handle:body()
            if body == nil then
                response_handle:logInfo(context .. "the body is nil")
                return
            end

            local len = body:length()
            if len == 0 then
                response_handle:logInfo(context .. "the length is 0")
                return
            end

            local body_str = body:getBytes(0, len)

            local url = "https://theme-park.plexmox.com/css/base/{{ .app }}/{{ .theme }}.css"
            local css_tag = '<link rel="stylesheet" type="text/css" href="' .. url .. '">'
            {{- if .head }}
            local new_body, count = string.gsub(body_str, "</head>", css_tag .. "</head>", 1)
            {{- else }}
            local new_body, count = string.gsub(body_str, "</body>", css_tag .. "</body>", 1)
            {{- end }}

            body:setBytes(new_body)
            response_handle:headers():replace("content-length", tostring(#new_body))
        end
{{- end }}
