middlewares:
  authelia:
    namespaces:
      - media
      - misc
      - traefik
      - docs
      - monitoring
      - default
      - longhorn-system
      - argo
  organizr:
    namespaces:
      - media
      - traefik
