{
 "title": "Longhorn",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>VOLUMES</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Number Of Volumes",
   "type": "stat",
   "description": "The total number of volumes in the Longhorn storage system",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_capacity_bytes) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Healthy Volumes",
   "type": "stat",
   "description": "Healthy volumes are volumes that are attaching to a node and have the number of healthy replicas equals to the expected number of replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==1) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Volume Actual Size/Capacity",
   "type": "timeseries",
   "description": "Note that Longhorn volume actual size is not the size of the filesystem inside a Longhorn volume.  See more at : https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (avg by (pvc) (longhorn_volume_actual_size_bytes))/ (avg by (pvc) (longhorn_volume_capacity_bytes)) ) *100",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "Number Of Degraded Volumes",
   "type": "stat",
   "description": "Degraded volumes are volumes that have the number of healthy replicas smaller than the expected number of replicas. e.g. User creates a volume with 2 replicas but 1 replicas is failed.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Fault Volumes",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "table",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (volume) (longhorn_volume_capacity_bytes)",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Number Of Attached Volumes",
   "type": "stat",
   "description": "Attached volumes are volumes that are currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Detached Volumes",
   "type": "stat",
   "description": "Detached volumes are volumes that aren't currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==3) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>NODES</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Number Of Nodes",
   "type": "stat",
   "description": "The total number of nodes in the Longhorn storage system",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(longhorn_node_count_total) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Disabled Nodes",
   "type": "stat",
   "description": "Disabled nodes are nodes that are disabled by the user.  When users disable a node, Longhorn will not use the node's storage for replica scheduling. Note that Longhorn can still attach a volume to disabled nodes because the actual data of the volume could be on a different node.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Node Storage Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number Of Schedulable Nodes",
   "type": "stat",
   "description": "Schedulable nodes are nodes that Longhorn can use their storage for replica scheduling.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(longhorn_node_status{condition=\"schedulable\"}==1) OR on() vector(0)) - (count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Number Of Failed Nodes",
   "type": "stat",
   "description": "Failed Nodes are nodes that Longhorn cannot attach volumes to and cannot schedule replicas onto. e.g: when the nodes went down.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(longhorn_node_count_total) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"}==1) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Node Capacity",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_node_storage_capacity_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of Volumes Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (node) (longhorn_volume_state==2)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>DISKS</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_disk_usage_bytes/longhorn_disk_capacity_bytes)*100",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "longhorn_disk_capacity_bytes", "legendFormat": "{{disk}}" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>CPU & MEMORY</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage/Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( longhorn_node_memory_usage_bytes / longhorn_node_memory_capacity_bytes ) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Instance Manager CPU Usage",
   "type": "timeseries",
   "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "milicpu" } },
   "targets": [
    {
     "expr": "longhorn_instance_manager_cpu_usage_millicpu",
     "legendFormat": "{{instance_manager}}"
    }
   ]
  },
  {
   "title": "Instance Manager CPU Usage/Request",
   "type": "timeseries",
   "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu)*100",
     "legendFormat": "{{instance_manager}}"
    }
   ]
  },
  {
   "title": "Instance Manager Memory Usage",
   "type": "timeseries",
   "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_instance_manager_memory_usage_bytes",
     "legendFormat": "{{instance_manager}}"
    }
   ]
  },
  {
   "title": "Longhorn Manager CPU Usage",
   "type": "timeseries",
   "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "milicpu" } },
   "targets": [
    {
     "expr": "longhorn_manager_cpu_usage_millicpu",
     "legendFormat": "{{manager}}"
    }
   ]
  },
  {
   "title": "Longhorn Manager Memory Usage",
   "type": "timeseries",
   "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_manager_memory_usage_bytes",
     "legendFormat": "{{manager}}"
    }
   ]
  }
 ]
}