{
 "title": "API",
 "tags": [ "srep" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shells",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(srep_shells_connected)", "legendFormat": "Shells" }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(srep_sockets_connected)", "legendFormat": "Shells" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(srep_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "srep_request_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shell Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(srep_request_duration_seconds_sum{url!=\"//plays/:id/shell\", url!=\"/plays/active/stream\"}[$__rate_interval])) / sum(rate(srep_request_duration_seconds_count{url!=\"//plays/:id/shell\", url!=\"/plays/active/stream\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(srep_pg_query_latency_milliseconds_sum[$__rate_interval])) / sum(rate(srep_pg_query_latency_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"srep/api\"} != `latency_human` | json | level = `error` | __error__=`` [$__auto])"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url) (srep_request_latency_seconds{url!=\"/plays/:id/shell\", url!=\"/plays/active/stream\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (query) (rate(srep_pg_query_latency_milliseconds_sum[$__rate_interval])) / sum by (query) (rate(srep_pg_query_latency_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shell Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Endpoint Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(url) (rate(srep_requests_total{job=\"api\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"srep\", container=\"api\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(queue) (srep_queue_ready)",
     "legendFormat": "Backlog: {{queue}}"
    },
    {
     "expr": "sum by(queue) (srep_queue_inflight)",
     "legendFormat": "Inflight: {{queue}}"
    },
    {
     "expr": "sum by(queue) (srep_queue_rejected)",
     "legendFormat": "Rejected: {{queue}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"srep\", container=\"api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays Expired",
   "type": "timeseries",
   "description": "The number of plays that are expired",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "plays" } },
   "targets": [
    {
     "expr": "round(sum(increase(srep_plays_killed[$__rate_interval])), 1)",
     "legendFormat": "Plays killed"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Access logs",
     "type": "logs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{job=\"srep/api\"} |= `latency_human` | json | __error__=``"
      }
     ]
    },
    {
     "title": "App Logs",
     "type": "logs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "{job=\"srep/api\"} != `latency_human` | json | __error__=``"
      }
     ]
    }
   ]
  },
  {
   "title": "APM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Route Statistics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "filters": [
        {
         "id": "72a36092",
         "operator": "=",
         "scope": "span",
         "tag": "kind",
         "value": [ "server" ],
         "valueType": "keyword"
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "api" ],
         "valueType": "string"
        },
        {
         "id": "c5d2b7fd",
         "operator": "!=",
         "scope": "span",
         "tag": "http.route",
         "value": [ "/*" ],
         "valueType": "string"
        }
       ],
       "groupBy": [
        { "id": "a3a06fe3", "scope": "span", "tag": "http.route" }
       ],
       "limit": 20,
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "filters": [
        {
         "id": "fa512e09",
         "operator": "=",
         "scope": "span",
         "tag": "kind",
         "value": [ "server" ],
         "valueType": "keyword"
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "api" ],
         "valueType": "string"
        }
       ],
       "groupBy": [
        { "id": "da299757", "scope": "span" }
       ],
       "limit": 20,
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Profiling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "flamegraph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "labelSelector": "{service_name=\"api\"}",
       "profileTypeId": "memory:inuse_space:bytes:space:bytes"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "flamegraph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "labelSelector": "{service_name=\"api\"}",
       "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
      }
     ]
    }
   ]
  }
 ]
}