---
middlewares:
  pocket:
    namespaces:
      - name: argo
        http:
          - argo
      - name: media
        http:
          - booklore

  authelia:
    namespaces:
      # - name: media
      #   http:
      #     - booklore
      - name: misc
        http:
          - garage-webui
          - speedtest
          - echo
      - name: docs
        http:
          - outline
      - name: monitoring
        http:
          - grafana
          - kube-prometheus-stack-alertmanager
          - vm-metrics
      - name: default
        http:
          - unraid
      - name: longhorn-system
        http:
          - longhorn

  organizr:
    namespaces:
      - name: media
        http:
          - prowlarr
          - sonarr
          - radarr
          - tautulli
          - transmission

bouncer:
  image:
    repository: ghcr.io/kdwils/envoy-proxy-bouncer
    tag: sha-dc5e8fa978ffc5814e8a553ce73489d42e80c8fc
  volumes:
    - name: crowdsec-tls
      secret:
        secretName: crowdsec-bouncer-tls
  volumeMounts:
    - name: crowdsec-tls
      mountPath: /etc/ssl/crowdsec
      readOnly: true
  config:
    bouncer:
      enabled: true
      metrics: true
      lapiURL: https://crowdsec-service.gateways.svc.cluster.local:8080
      tls:
        certPath: /etc/ssl/crowdsec/tls.crt
        keyPath: /etc/ssl/crowdsec/tls.key
        caPath: /etc/ssl/crowdsec/ca.crt
