---
middlewares:
  pocket:
    namespaces:
      - name: argo
        http:
          - argo
      - name: media
        http:
          - booklore

  authelia:
    namespaces:
      # - name: media
      #   http:
      #     - booklore
      - name: misc
        http:
          - garage-webui
          - speedtest
          - echo
      - name: docs
        http:
          - outline
      - name: monitoring
        http:
          - grafana
          - kube-prometheus-stack-alertmanager
          - vm-metrics
      - name: default
        http:
          - unraid
      - name: longhorn-system
        http:
          - longhorn

  organizr:
    namespaces:
      - name: media
        http:
          - prowlarr
          - sonarr
          - radarr
          - tautulli
          - transmission

bouncer:
  image:
    repository: ghcr.io/kdwils/envoy-proxy-bouncer
    tag: sha-dc5e8fa978ffc5814e8a553ce73489d42e80c8fc
  volumes:
    - name: crowdsec-tls
      secret:
        secretName: crowdsec-bouncer-tls
  volumeMounts:
    - name: crowdsec-tls
      mountPath: /etc/ssl/crowdsec
      readOnly: true
  config:
    trustedProxies:
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/12
      - 172.64.0.0/13
      - 131.0.72.0/22
      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
      - 10.0.0.0/8
    bouncer:
      enabled: true
      metrics: true
      lapiURL: https://crowdsec-service.gateways.svc.cluster.local:8080
      tls:
        certPath: /etc/ssl/crowdsec/tls.crt
        keyPath: /etc/ssl/crowdsec/tls.key
        caPath: /etc/ssl/crowdsec/ca.crt
