pod-gateway:
  controllers:
    main:
      containers:
        gluetun:
          enabled: true
          env:
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_INTERFACE
              value: wg0
            - name: FIREWALL
              value: "off"
            - name: DOT
              value: "off"
            # - name: HEALTH_VPN_DURATION_INITIAL
            #   value: 30s
            # - name: HEALTH_TARGET_ADDRESS
            #   value: "1.1.1.1"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: vpn-gateway-secrets
                  key: private_key
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: vpn-gateway-secrets
                  key: addresses
            - name: WIREGUARD_ENDPOINT_IP
              valueFrom:
                secretKeyRef:
                  name: vpn-gateway-secrets
                  key: server_ip
            - name: WIREGUARD_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: vpn-gateway-secrets
                  key: server_public_key

  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.43.0.0/16 10.0.0.0/24"
    VPN_LOCAL_CIDRS: 10.0.0.0/8

  DNSPolicy: ClusterFirst

  routed_namespaces:
    - tunneled
