---
# yaml-language-server: $schema=https://raw.githubusercontent.com/henrywhitaker3/crds/refs/heads/main/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate-operator
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: misc
    server: https://kubernetes.default.svc
  project: apps
  sources:
    - repoURL: https://gitlab.com/henrywhitaker3/homelab.git
      targetRevision: main
      ref: values
    - repoURL: oci://ghcr.io/mogenius/helm-charts/renovate-operator
      path: .
      # renovate: datasource=github-releases depName=mogenius/renovate-operator
      targetRevision: 4.3.1
      helm:
        valueFiles:
          - $values/kubernetes/k3s/apps/misc/renovate-operator/values.yaml
    - repoURL: https://gitlab.com/henrywhitaker3/homelab.git
      targetRevision: main
      path: kubernetes/k3s/apps/misc/renovate-operator/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
