---
- name: Remove old repo
  become: "{{ netbird_become }}"
  tags: netbird
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pkgs_netbird_io_debian.list
    state: absent

- name: Add netbird apt repository
  tags: netbird
  become: "{{ netbird_become }}"
  ansible.builtin.deb822_repository:
    name: netbird
    types: deb
    uris: https://pkgs.netbird.io/debian
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://pkgs.netbird.io/debian/public.key
    state: present

- name: Install netbird packages
  tags: netbird
  become: "{{ netbird_become }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - netbird

- name: Enabled netbird service
  tags: netbird
  become: "{{ netbird_become }}"
  ansible.builtin.command:
    cmd: "netbird service start"
  changed_when: true

- name: Connect to netbird
  tags: netbird
  become: "{{ netbird_become }}"
  ansible.builtin.command:
    cmd: "netbird up --management-url {{ netbird_url }} --setup-key {{ netbird_setup_key }}"
  register: up
  until: "up is not failed"
  retries: 10
  delay: 15
  changed_when: true
