---
# yaml-language-server: $schema=https://henrywhitaker3.github.io/generic-helm-chart/subchart.schema.json
generic:
  replicaCount: 1

  image:
    repository: outlinewiki/outline
    pullPolicy: IfNotPresent
    tag: "1.7.1"

  service:
    port: 3000

  httpRoute:
    enabled: true
    annotations:
      gaptime.henrywhitaker.com/monitor: "true"
      gaptime.henrywhitaker.com/code: "401"
      gaptime.henrywhitaker.com/resolver: "1.1.1.1"
    hostnames: [docs.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: gateways
    rules:
      - port: 3000
        matches:
          - path:
              type: PathPrefix
              value: /

  pvc:
    enabled: true
    mountPath: /var/lib/outline/data
    storageClassName: longhorn
    size: 256M

  deploymentStrategy:
    type: Recreate

  probes:
    initialDelaySeconds: 30
    timeoutSeconds: 3

  config:
    NODE_ENV: production
    FORCE_HTTPS: "false"
    REDIS_URL: redis://dragonfly.dragonfly.svc:6379/2
    PGSSLMODE: disable
    URL: https://docs.plexmox.com

    FILE_STORAGE: local
    FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
    FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"

    OIDC_CLIENT_ID: 3c8a4ad7-f75b-4e1a-8263-45d554964582
    OIDC_AUTH_URI: https://pocket.plexmox.com/authorize
    OIDC_TOKEN_URI: https://pocket.plexmox.com/api/oidc/token
    OIDC_USERINFO_URI: https://pocket.plexmox.com/api/oidc/userinfo
    OIDC_USERNAME_CLAIM: preferred_username
    OIDC_DISPLAY_NAME: Pocket
    OIDC_SCOPES: "openid offline_access profile email"

  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: outline
          key: secret-key
    - name: UTILS_SECRET
      valueFrom:
        secretKeyRef:
          name: outline
          key: utils-secret
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: crunchy-pguser-outline
          key: uri
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: outline
          key: pocket-client-secret

  securityContext:
    runAsUser: 0

  secrets:
    enabled: true
    key: outline-secrets
